### PR TITLE
added action resetTo

### PR DESCRIPTION
**Pull request by lucasfeliciano**
related to #5

### CODE REVIEW

**Comment by lucasfeliciano** [comment]
related to #5

**Comment by Kureev** [comment]
Something super-weird happens here...

**Comment by Kureev** [comment]
Don't mind, I'll clean it up and merge it in.
ETA: Today

**Comment by lucasfeliciano** [comment]
yeah, I keep losing my git user config.

and I had to fix the conflicts like 3 times.

**Comment by lucasfeliciano** [comment]
you merged #12 into this branch as well.

**Pull request closed without merging**
